version: '3'
services:
  cockroach:
    container_name: cockroach
    hostname: cockroach
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - '/data/cockroach:/data/cockroach'
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure

  redis:
    container_name: keycat_redis
    image: redis:alpine
    ports:
      - 6379:6379
