version: '3'
services:
  postgres:
    container_name: keycat_pg
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycat
  redis:
    container_name: keycat_redis
    image: redis:alpine
    ports:
      - 6379:6379
